[package]
name = "os-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"

[[bench]]
name = "rand_string_bench"
harness = false

[[bench]]
name = "simd_vs_scalar"
harness = false